blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='dic'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^group_make/$',views.group_make,name='group_make'),
	url(r'^group/(?P<url>\w+)/$',views.group,name='group'),#url변수에 모든 값을 넣어 ㅂ뷰로 전송
    url(r'^group/(?P<url>\w+)/group_invitation/$',views.group_invitation,name='group_invitation'),
	url(r'^group_list$',views.group_list,name='group_list'),
    url(r'^post/(?P<url>\w+)/new/$',views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),

    url(r'^post/chat_room/vote/new/(?P<pk>\d+)/$',views.vote_new,name='vote_new'),
    url(r'^post/chat_room/vote/(?P<pk>\d+)/(?P<id>\d+)/$',views.vote,name='vote'),
    url(r'^post/chat_room/vote_list/(?P<pk>\d+)/$',views.vote_list,name='vote_list'),
    url(r'^post/chat_room/vote_result/(?P<id>\d+)/$',views.vote_result,name='vote_result'),
    
    url(r'^post/file/new/(?P<pk>\d+)/$',views.file_new,name='file_new'),  
    #url(r'^post/file/list/(?P<pk>\d+)/$',views.file_list,name='file_list'),  
    url(r'^post/file/list2/(?P<pk>\d+)/$',views.file_list2,name='file_list2'),
    url(r'^post/file/list3/(?P<pk>\d+)/$',views.file_list3,name='file_list3'),

    url(r'^post/chat_room/task/new/(?P<pk>\d+)/$',views.task_new,name='task_new'),
    url(r'^post/chat_room/task_list/(?P<pk>\d+)/$',views.task_list,name='task_list'),

    url(r'^post_list/$', views.post_list, name='post_list'),
    url(r'^sign_up/$', views.signup, name='sign_up'),
    url(r'^sign_in/$', views.signin, name='sign_in'),
    url('^sign_out/$', auth_views.logout, {'next_page' : '/'}),
    

    url(r'^post/chat_room/(?P<pk>\d+)/$', views.chat_room, name='chat_room'),
    url(r'^post/chat_room/(?P<pk>\d+)/posting/$', views.posting, name='posting'),
    url(r'^messages/$', views.messages, name='messages'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace="blog")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

class Group(models.Model):
  group_name = models.CharField(max_length=100)
  group_link = models.CharField(max_length=100, null=True)
  url = models.CharField(max_length=50, primary_key=True)
  created_date = models.DateTimeField(default=timezone.now)
  published_date = models.DateTimeField(blank=True, null=True)
  user = models.ManyToManyField('auth.User',related_name='user', default=None)

  def __str__(self):
    return self.group_name

class Post(models.Model):
  author = models.ForeignKey('auth.User', on_delete=models.PROTECT)
  title = models.CharField(max_length=200)
  text = models.TextField()
  created_date = models.DateTimeField(default=timezone.now)
  published_date = models.DateTimeField(blank=True, null=True)
  group = models.ForeignKey(Group,related_name='posts',null=True)

  def publish(self):
    self.published_date = timezone.now()
    self.save()

  def __str__(self):
    return self.title

class Vote(models.Model):
  post = models.ForeignKey(Post,related_name='votes',null=True)
  user=models.ManyToManyField('auth.User',related_name='vote_user', default=None)
  vote_title = models.CharField(max_length=200)
  vote_text = models.TextField()
  vote_num = models.IntegerField(null=True)
  num = models.IntegerField(default=0)
  agree = models.IntegerField(default=0)
  disagree = models.IntegerField(default=0)
  nothing = models.IntegerField(default=0)
  created_date = models.DateTimeField(default=timezone.now)
  published_date = models.DateTimeField(blank=True, null=True)
  def __str__(self):
    return self.vote_title

class Document(models.Model):
  post = models.ForeignKey(Post,related_name='files',null=True)
  user = models.ForeignKey('auth.User',related_name='doucu_user')
  docu_title = models.CharField(max_length=200)
  docfile = models.FileField()
  importance = models.CharField(max_length=100,null=True)
  published_date = models.DateTimeField(blank=True,null=True)

class Task(models.Model):
  post = models.ForeignKey(Post,related_name='takes',null=True)
  user = models.ForeignKey('auth.User',related_name='users')
  thisUser = models.TextField(null=True)
  toDo = models.TextField(null = False)
  deadline = models.TextField()

class Chat(models.Model):
  post = models.ForeignKey(Post)
  created = models.DateTimeField(auto_now_add=True)
  message = models.CharField(max_length=255)
  user = models.ForeignKey(User)

  def __str__(self):
    return self.message

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
#from django.forms import formset_factory
from .models import Post,Group,Vote,Document,Task,Chat
from django.contrib.auth.models import User

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('group_name','group_link',)

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'text',)

class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ('vote_title','vote_text','vote_num',)

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('docu_title','importance',)
class doVoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields=()


class UserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'password']
    widgets = {
            'username': forms.TextInput(attrs={'placeholder':'Name'}),
            'email': forms.EmailInput(attrs={'placeholder':'Email'}),
            'password' : forms.PasswordInput(attrs={'placeholder':'Password'}),
        }


class LoginForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username', 'password'] # 로그인 시에는 유저이름과 비밀번호만 입력 받는다.
    widgets = {
            'username': forms.TextInput(attrs={'placeholder':'Name'}),
            'password' : forms.PasswordInput(attrs={'placeholder':'Password'}),
        }

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['toDo','thisUser','deadline']

blog/views.py
#-*- coding: utf-8 -*-
import json
import urllib
import urllib.request
import urllib.parse
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.template import RequestContext

#모델 및 폼
from .models import Post, Group, Vote, Document, Task, Chat
from django.contrib.auth.models import User, AnonymousUser
from django.contrib.auth import login, authenticate
from .forms import PostForm, UserForm, LoginForm, GroupForm, VoteForm,doVoteForm, DocumentForm, TaskForm
from django.utils import timezone

from .group import *



def index(request):
	isuser = 0
	return render(request, 'blog/index.html', {'isuser':isuser})

def group_make(request):
    ran = Random_make()
    a = ran.random_url()
    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            #group.url = group.group_link[28:40]
            #group.url = group.group_link[45:57]#파이썬애니웨어
            group.url = group.group_link[30:42]#서버배포
            group.published_date = timezone.now()
            group.save()
            user = get_object_or_404(User,username=request.user)
            #group2 = get_object_or_404(Group, url = group.url)
            group.user.add(user)
            return redirect('dic:group', url=group.url)
    else:
        form = GroupForm()
    return render(request, 'blog/group_make.html',{'a':a, 'form':form})

def group_list(request):
    groups = Group.objects.filter(user=request.user)
    return render(request,'blog/group_list.html', {'groups':groups})

def group(request,url):
    group = get_object_or_404(Group, url = url)
    #if group.user.all().find != request.user:
            #return redirect('group_invitation/', url= group.url)
    return render(request,'blog/group.html',{'group':group})

def group_invitation(request, url):
    group = get_object_or_404(Group, url = url)
    try:
        user = User.objects.get(username=request.user)
        group.user.add(user)
    except User.DoesNotExist:
        redirect('/sign_in')

    return render(request, 'blog/group_invitation.html',{'group':group})

def post_new(request,url):
    group = get_object_or_404(Group, url = url)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.group = group
            post.save()
            return redirect('dic:group', url=group.url)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})
def post_list(request):
	posts = Post.objects.select_Related('group')
	return render(request, 'blog/post_list.html', {'posts': posts})
	
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def vote_new(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method=="POST":
        form = VoteForm(request.POST)
        if form.is_valid():
            vote = form.save(commit=False)
            vote.published_date = timezone.now()
            vote.post = post
            vote.save()
            #return redirect('dic:vote',pk  =post.pk,id = vote.id)
            return redirect('dic:vote_list',pk=post.pk)

    else:
        form = VoteForm()
    return render(request,'blog/vote_edit.html',{'post':post,'form':form})
    
def vote_list(request,pk):
    post = get_object_or_404(Post,pk=pk)
    return render(request, 'blog/vote_list.html', {'post': post})

def vote_result(request,id):
    vote = get_object_or_404(Vote,id=id)
    return render(request,'blog/vote_result.html',{'vote':vote})

def vote(request,pk,id):
    post = get_object_or_404(Post,pk=pk)
    vote = get_object_or_404(Vote,id=id)
    if 'value1' in request.POST:
        form = doVoteForm(request.POST)
        dovote = form.save(commit=False)
        dovote.id = vote.id
        dovote.vote_title = vote.vote_title
        dovote.vote_text = vote.vote_text
        dovote.vote_num = vote.vote_num
        dovote.post = vote.post
        dovote.agree = vote.agree+1
        dovote.disagree = vote.disagree
        dovote.nothing = vote.nothing
        dovote.num = vote.num+1
        dovote.save()
        user = get_object_or_404(User,username=request.user)
        dovote.user.add(user)
        return redirect('dic:vote_list',pk=post.pk)
    elif 'value2' in request.POST:
        form = doVoteForm(request.POST)
        if form.is_valid():
            dovote = form.save(commit=False)
            dovote.id = vote.id
            dovote.vote_title = vote.vote_title
            dovote.vote_text = vote.vote_text
            dovote.vote_num = vote.vote_num
            dovote.post = vote.post            
            dovote.disagree = vote.disagree+1
            dovote.agree = vote.agree
            dovote.nothing = vote.nothing
            dovote.num = vote.num+1
            dovote.save()
            user = get_object_or_404(User,username=request.user)
            dovote.user.add(user)
            return redirect('dic:vote_list',pk=post.pk)
    elif 'value3' in request.POST:
        form = doVoteForm(request.POST)
        if form.is_valid():
            dovote = form.save(commit=False)
            dovote.id = vote.id
            dovote.vote_title = vote.vote_title
            dovote.vote_text = vote.vote_text
            dovote.vote_num = vote.vote_num
            dovote.post = vote.post 
            dovote.nothing = vote.nothing+1
            dovote.disagree = vote.disagree
            dovote.agree = vote.agree
            dovote.num = vote.num+1
            dovote.save()
            user = get_object_or_404(User,username=request.user)
            dovote.user.add(user)
            return redirect('dic:vote_list',pk=post.pk)
    else:
        form = doVoteForm()

    return render(request,'blog/vote.html',{'post':post,'vote':vote,'form':form})

def file_new(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == "POST":
        form = DocumentForm(request.POST,request.FILES)
        if form.is_valid():
            newdoc = form.save(commit=False)
            newdoc.docfile = request.FILES['docfile']
            newdoc.post = post
            newdoc.user = request.user
            newdoc.published_date=timezone.now()
            newdoc.save()
            return redirect('dic:file_list2',pk=post.pk)
    else:
        form = DocumentForm()
    return render(request,'blog/file_new.html',{'post':post,'form':form})

'''def file_list(request,pk):
    post = get_object_or_404(Post,pk=pk)
    return render(request,'blog/file_list.html',{'post':post})'''

def file_list2(request,pk):
    post = get_object_or_404(Post,pk=pk)
    documents = post.files.all()
    return render(request,'blog/file_list2.html',{'post':post,'documents':documents})

def file_list3(request,pk):
    post = get_object_or_404(Post,pk=pk)
    documents = post.files.all().order_by('-published_date')
    return render(request,'blog/file_list3.html',{'post':post,'documents':documents})

def task_new(request,pk):
    post = get_object_or_404(Post,pk=pk)
    group = post.group
    users = group.user.all() 

    if request.method=="POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.post = post
            task.user = request.user
            task.save()
            #return redirect('/')
            return redirect('dic:task_list', pk=post.pk)
    else:
        form = TaskForm()
    return render(request,'blog/task_new.html',{'post':post,'form':form, 'users':users})

def task_list(request, pk):
    post = get_object_or_404(Post,pk=pk)
    group = post.group
    users = group.user.all()
    tasks = Task.objects.filter(post = post).order_by('deadline')
    return render(request, 'blog/task_list.html', {'post': post, 'users':users, 'tasks':tasks})


def signup(request):
    if request.method == "POST":
    	form = UserForm(request.POST)
    	print(form)
    	if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('/')
    	else:
    		isuser = 1
    		return render(request, 'blog/sign_up.html', {'form': form, 'isuser':isuser})
    else:
    	isuser = 1
    	form = UserForm()
    	return render(request, 'blog/sign_up.html', {'form': form, 'isuser':isuser})

def signin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
        	isuser = 1
        	return HttpResponse('로그인 실패. 다시 시도 해보세요.')
    else:
        form = LoginForm()
        isuser = 1
        return render(request, 'blog/sign_in.html', {'form': form, 'isuser':isuser})

def chat_room(request,pk):
    post = get_object_or_404(Post,pk=pk)
    chats = Chat.objects.filter(post=post)
    ctx = {
        'chat_room': 'active',
        'chat': chats,
        'post': post,
    }
    return render(request, 'blog/chat_room.html', ctx)
    
def posting(request, pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == "POST":
        msg = request.POST.get('msgbox', None)
        print('Our value = ', msg)
        chat_message = Chat(user=request.user, message=msg, post=post)
        msg = chat_message.user.username+": "+msg
        chat_message = Chat(user=request.user, message=msg, post=post)
        if msg != '':
            chat_message.save()
        return JsonResponse({'msg': msg, 'user': chat_message.user.username})
    else:
        return HttpResponse('Request must be POST.')

blog/templates/blog/file_list.html
{% extends 'blog/sub.html' %}
{% load staticfiles%}
{% block content %}
<link rel="stylesheet" href="{% static 'css/file.css'  %}">
<div class='sub_nav'>
    <ul>
        <li><a href="{% url 'dic:group' url=post.group.url %}">{{post.group.group_name}}</a></li>
        <li class="breaker"> > </li>
        <li><a href="{% url 'dic:post_detail' pk=post.pk %}">{{post.title}}</a></li>
        <li class="breaker"> > </li>
        <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">공유 문서함</a>
            <div class="dropdown-content">
                <a href="{% url 'dic:chat_room' pk=post.pk %}">Chat</a>
                <a href="{% url 'dic:task_list' pk=post.pk%}">업무 분담표</a>
            </div>
        </li>
    </ul>
</div>

<div class="file_link">
	<a href="{% url 'dic:file_list2' pk=post.pk %}">중요도순 보기</a>
	<p></p>
	<a href="{% url 'dic:file_list3' pk=post.pk %}">시간순 보기</a>
</div>

{% endblock %}

blog/templates/blog/file_new.html
{% extends 'blog/sub.html' %}
{% block content %}
<div class='sub_nav'>
    <ul>
        <li><a href="{% url 'dic:group' url=post.group.url %}">{{post.group.group_name}}</a></li>
        <li class="breaker"> > </li>
        <li><a href="{% url 'dic:post_detail' pk=post.pk %}">{{post.title}}</a></li>
        <li class="breaker"> > </li>
        <li class="dropdown">
            <a href="{% url 'dic:chat_room' pk=post.pk %}" class="dropbtn">Chat</a>
            <div class="dropdown-content">
                <a href="{% url 'dic:task_list' pk=post.pk %}">업무 분담표</a>
                 <a href="{% url 'dic:file_list2' pk=post.pk%}">공유 문서함</a>
            </div>
        </li>
        <li class="breaker"> : </li>
            <li><a href="{% url 'dic:vote_new' pk=post.pk %}">투표 생성</a></li>
            <li class="breaker"> | </li>
            <li><a href="{%url 'dic:vote_list' pk=post.pk %}">투표 목록</a></li>
            <li class="breaker"> | </li>
            <li><a href="{% url 'dic:task_new' pk=post.pk %}">업무 분담</a></li>
            <li class="breaker"> | </li>
            <li class="select"><a href="{%url 'dic:file_new' pk=post.pk %}">문서 공유</a></li>
    </ul>
</div>


<div class="post_edit" align="center">
	    <form method="POST" class="post-form" enctype="multipart/form-data">
	    	{% csrf_token %}
	    	<input type="text" size='40' name="docu_title" placeholder="제목을 입력해주세요" requierd>
	    	<br><br>
	    	<h4>중요도 선택</h4>
	    	<select name="importance">
	    			<option value='high'>상</option>
	    			<option value='middle'>중</option>
	    			<option value='low'>하</option>
	    	</select>
	    	<br><br>
	    	<input type="file" name="docfile">
	    	<br><br>    	
	        <button type="submit" class="save btn btn-default">Save</button>
	    </form>

</div>
<script>
	$(".post-form > p > input").attr("class","fInput");

	// $( ".wrapInput" ).prepend( "<div class=\"input-label\">TITLE</div>" );
</script>
{% endblock %}

blog/templates/blog/group.html
{% extends 'blog/sub.html' %}
{% load staticfiles%}
{% block content %}
 <link rel="stylesheet" href="{% static 'css/group.css'  %}">
<div class='sub_nav'>
    <ul>
    	<li><a href="{% url 'dic:group' url=group.url %}">{{group.group_name}}</a></li>
	</ul>
</div>



<div class = "group_user">
	<h2 align="center"><span style="color:#86119a">'{{group.group_name}}'</span> 의 그룹입니다.</h2>
	{%for name in group.user.all%}
	<div>
		<img src="../../../static/image/user.png" height = 7% width = 7%></img>
		<p>{{name.username}}</p>
	</div>
	{% endfor %}
</div>


<div class = "post_list">
	<h1 align="center">토의 주제 List</h1>

	<a  href="{% url 'dic:post_new' url=group.url %}" ><button>토의 주제 작성하기☞</button></a>
	    {% for post in group.posts.all %}
	    <ul class=container>
	        <li>
	        	<a href="{% url 'dic:post_detail' pk=post.pk %}" >
	        		<h3 class="title">{{ post.title }}</h3>
	        		<h4 class="sub">{{ post.text }}</h4>
	        	</a>
	        </li>
	    </ul>
	    {% endfor %}
</div>


{% endblock %}

blog/templates/blog/task_new.html
{% extends 'blog/sub.html' %}
{% block content %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script>

  $( function() {

    $( "#datepicker" ).datepicker();

  } );

  </script>

<div class='sub_nav'>
    <ul>
        <li><a href="{% url 'dic:group' url=post.group.url %}">{{post.group.group_name}}</a></li>
        <li class="breaker"> > </li>
        <li><a href="{% url 'dic:post_detail' pk=post.pk %}">{{post.title}}</a></li>
        <li class="breaker"> > </li>
        <li class="dropdown">
            <a href="{% url 'dic:chat_room' pk=post.pk %}" class="dropbtn">Chat</a>
            <div class="dropdown-content">
                <a href="{% url 'dic:task_list' pk=post.pk %}">업무 분담표</a>
                 <a href="{% url 'dic:file_list2' pk=post.pk%}">공유 문서함</a>
            </div>
        </li>
        <li class="breaker"> : </li>
            <li><a href="{% url 'dic:vote_new' pk=post.pk %}">투표 생성</a></li>
            <li class="breaker"> | </li>
            <li><a href="{%url 'dic:vote_list' pk=post.pk %}">투표 목록</a></li>
            <li class="breaker"> | </li>
            <li class="select"><a href="{% url 'dic:task_new' pk=post.pk %}">업무 분담</a></li>
            <li class="breaker"> | </li>
            <li><a href="{%url 'dic:file_new' pk=post.pk %}">문서 공유</a></li>
    </ul>
</div>



<div class="post_edit" align="center">
	{% if not user.is_authenticated %}
	<h1>x업무분담을 진행하시려면 로그인이 필요합니다.</h1>
	<h2><a href="/sign_in">로그인 하러가기 Click!</a></h2>
	{% else %}
	    <h1>"{{ post.title }}"</h1>
	    <h3>위 주제와 관련한 업무를 분담해주세요.</h3>
	    <form method="POST" class="post-form" >
	    	{% csrf_token %}
	    	<select name="thisUser">
	    		{%for user in users%}
	    			<option value='{{user.username}}'>{{user.username}}</option>
	    		{%endfor%}
	    	</select>
	    	<input type="text" size='50' name="toDo" placeholder="업무를 키워드 중심으로 입력해주세요" requierd>
	    	Deadline: <input type="text" name="deadline" id="datepicker">
	    	<button type="submit" class="save btn btn-default">Save</button>

	    </form>
    {% endif %}

</div>


{%endblock%}

blog/templates/blog/vote.html
{% extends 'blog/sub.html' %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/vote.css'  %}">
{%if request.user not in vote.user.all %}

<div class='sub_nav'>
    <ul>
        <li><a href="{% url 'dic:group' url=post.group.url %}">{{post.group.group_name}}</a></li>
        <li class="breaker"> > </li>
        <li><a href="{% url 'dic:post_detail' pk=post.pk %}">{{post.title}}</a></li>
        <li class="breaker"> > </li>
        <li class="dropdown">
            <a href="{% url 'dic:chat_room' pk=post.pk %}" class="dropbtn">Chat</a>
            <div class="dropdown-content">
                <a href="{% url 'dic:task_list' pk=post.pk %}">업무 분담표</a>
                <a href="{% url 'dic:file_list2' pk=post.pk %}">공유 문서함</a>
            </div>
        </li>
        <li class="breaker"> : </li>
            <li><a href="{% url 'dic:vote_new' pk=post.pk %}">투표 생성</a></li>
            <li class="breaker"> | </li>
            <li><a href="{%url 'dic:vote_list' pk=post.pk %}">투표 목록</a></li>
            <li class="breaker"> | </li>
            <li><a href="{% url 'dic:task_new' pk=post.pk %}">업무 분담</a></li>
            <li class="breaker"> | </li>
            <li><a href="{%url 'dic:file_new' pk=post.pk %}">문서 공유</a></li>
    </ul>
</div>


<div class="vote">
	<h1>"{{vote.vote_title}}"</h1>
	<h3>{{vote.vote_text}}</h3>
		<div>
			<form method='POST'>
			    {% csrf_token %}
				<input type="submit" name='value1' VALUE='찬성'>
				<input type="submit" name='value2' VALUE='반대'>
				<input type="submit" name='value3' VALUE='보류'>
			</form>
		</div>
	{%else%}
		<h3>이미 참여 하셨습니다.</h3>
	{%endif%}
</div>
{%endblock%}

blog/templates/blog/vote_list.html
{% extends 'blog/sub.html' %}
{% load staticfiles%}
{% block content %}

<link rel="stylesheet" href="{% static 'css/vote.css'  %}">
<div class='sub_nav'>
    <ul>
        <li><a href="{% url 'dic:group' url=post.group.url %}">{{post.group.group_name}}</a></li>
        <li class="breaker"> > </li>
        <li><a href="{% url 'dic:post_detail' pk=post.pk %}">{{post.title}}</a></li>
        <li class="breaker"> > </li>
        <li class="dropdown">
            <a href="{% url 'dic:chat_room' pk=post.pk %}" class="dropbtn">Chat</a>
            <div class="dropdown-content">
                <a href="{% url 'dic:task_list' pk=post.pk %}">업무 분담표</a>
                <a href="{% url 'dic:file_list2' pk=post.pk%}">공유 문서함</a>
            </div>
        </li>
        <li class="breaker"> : </li>
            <li><a href="{% url 'dic:vote_new' pk=post.pk %}">투표 생성</a></li>
            <li class="breaker"> | </li>
            <li class="select"><a href="{%url 'dic:vote_list' pk=post.pk %}">투표 목록</a></li>
            <li class="breaker"> | </li>
            <li><a href="{% url 'dic:task_new' pk=post.pk %}">업무 분담</a></li>
            <li class="breaker"> | </li>
            <li><a href="{%url 'dic:file_new' pk=post.pk %}">문서 공유</a></li>
    </ul>
</div>


<h1></h1>
<div class="vote_list">
    {% for vote in post.votes.all %}
    <div class=container>
        	{%if vote.vote_num != vote.num %}
        			<p class="vote_ing" ><a href="{% url 'dic:vote' pk=post.pk id=vote.id %}">[진행중 투표] {{ vote.vote_title }}</a></p>
        	{%else%}
        			<p class="vote_ed"><a href="{% url 'dic:vote_result' id=vote.id %}">[완료된 투표] {{ vote.vote_title }}</a></p>
        	{% endif %}
    </div>
    {% endfor %}
</div>
{% endblock %}